### ISSUE TITLE
CRITICAL ERROR: Please compile the segmentation algorithm before running this script.

### ISSUE THREAD

**Issue by MohammedHAlali** [manuel-munoz-aguirre/PyHIST#24]
Hello,
I cloned PyHIST github repository and then I'm running PyHIST as a script.
When I give it his command:
`python pyhist.py GTEX-1117F-1026.svs`
I get this error:
`09-04-2021 00:33:28 [CRITICAL]: Please compile the segmentation algorithm before running this script. Exiting.`

I also tried creating a conda environment with all required libraries and also faced the same error mentioned above.

How can "I compile the algorithm"?
Thank you,
Mohammed

**Comment by manuel-munoz-aguirre** [comment]
Hi Mohammed,
Can you give more information about how you're running PyHIST (OS, etc.)? Did you use the conda environment bundled together with PyHIST or a different one? This message should pop up when the internal method used to segment the images was not compiled for some reason (which should happen automatically upon launching PyHIST for the first time). Try going to `src/graph_segmentation/` and run `make`, which should take care of this. Please let us know if this doesn't solve it.

**Comment by MohammedHAlali** [comment]
Hi Manuel,
Thanks for replying.
I'm running in on Command Prompt on Windows 10 Home.
I tried to use the conda environment but had difficulty installing OpenSlide. Then, I used PyHIST directly from the source code.
My steps are:
1- `git clone https://github.com/manuel-munoz-aguirre/PyHIST.git`
2- `cd PyHIST`
3- I brought an svs image, GTEX-1117F-1026.svs
4- 
`C:\Users\moham\Documents\PyHIST>python pyhist.py GTEX-1117F-1026.svs`

`09-04-2021 23:10:37 [CRITICAL]: Please compile the segmentation algorithm before running this script. Exiting.
`

I tried going to `src/graph_segmentation/` and running `make`, then got this:
![pyhist](https://user-images.githubusercontent.com/33809125/114258081-cb945f80-9989-11eb-9b01-65c891d5e466.PNG)

**Comment by manuel-munoz-aguirre** [comment]
The conda environment we provide is only supported for macOS/Linux (see [here](https://github.com/manuel-munoz-aguirre/PyHIST#conda-environment-linuxmacos)). We support PyHIST in Windows only through a [docker image](https://github.com/manuel-munoz-aguirre/PyHIST#docker).
