### ISSUE TITLE
Padded tiles

### ISSUE THREAD

**Issue by franfcunha** [manuel-munoz-aguirre/PyHIST#26]
Hi @manuel-munoz-aguirre 
Thank you for this amazing tool :)

I was wondering if your program handles padding in case of the image is not divisible by a given tilesize.
How does the system deals with this?

Thank youuu

**Comment by manuel-munoz-aguirre** [comment]
Hi,
By default, tiles (towards the right and bottom edges of the image) that do not meet the tile size are dropped out. These tiles can be saved with the `--save-nonsquare` flag, but they will be output at their actual size (i.e. not padded).

**Comment by franfcunha** [comment]
Muchas gracias :+1:
